// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ufezwsgjhzaueuwlbcfa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVmZXp3c2dqaHphdWV1d2xiY2ZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3NzY5OTQsImV4cCI6MjA2OTM1Mjk5NH0.V7wLUFom47fNH_O6mG980KjYjCBUOLBbbVhwn3SCFa4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});